spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jparealworld
#    url: jdbc:h2:mem:jparealworld;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: vRA3AY4apMyOfJ8EtJVX

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true